export const ATC_HUMAN_MAPPING: Record<string, { label: string; color: string }> = {
  "A10C1": { label: "Insulina, ação rápida", color: "emerald" },
  "A10C2": { label: "Insulina, ação interme...", color: "emerald" },
  "A10C3": { label: "Insulina, ação interme...", color: "emerald" },
  "A10H": { label: "Antidiabético sulfonil...", color: "emerald" },
  "A10J1": { label: "Antidiabético biguanidas", color: "emerald" },
  "A10J2": { label: "Assoc. antidiabético s...", color: "emerald" },
  "A10K1": { label: "Antidiabético glitazonas", color: "emerald" },
  "A10L": { label: "Antidiabético inibidor...", color: "emerald" },
  "A10M1": { label: "Antidiabético glinidas", color: "emerald" },
  "A10N1": { label: "Antidiabético inibidor...", color: "emerald" },
  "A10N3": { label: "Assoc. inibidores dpp-...", color: "emerald" },
  "A10N9": { label: "Outras assoc. antidiab...", color: "emerald" },
  "A10P1": { label: "Antidiabético inibidor...", color: "emerald" },
  "A10P3": { label: "Assoc. antidiabético i...", color: "emerald" },
  "A10P5": { label: "Assoc. antidiabéticas ...", color: "emerald" },
  "A10S": { label: "Antidiabético agonista...", color: "emerald" },
  "A10X9": { label: "Outros medicamentos us...", color: "emerald" },
  "A11A4": { label: "Outros polivitamínicos...", color: "emerald" },
  "A11B4": { label: "Polivitamínicos sem mi...", color: "emerald" },
  "A11C1": { label: "Vit. a", color: "emerald" },
  "A11C2": { label: "Vit. d", color: "emerald" },
  "A11C3": { label: "Assoc. vit.s a com d", color: "emerald" },
  "A11D3": { label: "Vit. b1", color: "emerald" },
  "A11D4": { label: "Assoc. vit. b1+ b6 e/o...", color: "emerald" },
  "A11E1": { label: "Complexo b", color: "emerald" },
  "A11F": { label: "Vit. b12", color: "emerald" },
  "A11G1": { label: "Vit. c", color: "emerald" },
  "A11G2": { label: "Assoc. com vit. c", color: "emerald" },
  "A11X2": { label: "Vit. b6 (pirodoxina)", color: "emerald" },
  "A11X3": { label: "Vit. e", color: "emerald" },
  "A11X9": { label: "Todas outras vit.s", color: "emerald" },
  "A12A": { label: "Produtos a base de cálcio", color: "emerald" },
  "A12B": { label: "Suplementos minerais á...", color: "emerald" },
  "A12C2": { label: "Outros suplementos min...", color: "emerald" },
  "A13A2": { label: "Todos os outros tônicos", color: "emerald" },
  "A14A1": { label: "Anabolizantes hormonais", color: "emerald" },
  "A15A": { label: "Orexígenos", color: "emerald" },
  "A16A": { label: "Outros produtos para o...", color: "emerald" },
  "A1A": { label: "Estomatológicos", color: "emerald" },
  "A1A3": { label: "Analgésicos e antiinfl...", color: "emerald" },
  "A1B": { label: "Antifúngicos s", color: "emerald" },
  "A2A1": { label: "Antiácidos", color: "emerald" },
  "A2A2": { label: "Antiflatulentos e carm...", color: "emerald" },
  "A2A4": { label: "Antiácidos com antifla...", color: "emerald" },
  "A2A6": { label: "Antiácidos com outros ...", color: "emerald" },
  "A2B1": { label: "Antagonistas receptore...", color: "emerald" },
  "A2B2": { label: "Protetor gástrico", color: "emerald" },
  "A2B9": { label: "Todos os outros antiul...", color: "emerald" },
  "A2C0": { label: "Outras preparações par...", color: "emerald" },
  "A3A": { label: "Antiespasmódico e anti...", color: "emerald" },
  "A3D": { label: "Assoc. antiespasmódico...", color: "emerald" },
  "A3E": { label: "Antiespasmódico associ...", color: "emerald" },
  "A3F": { label: "Gastroprocinéticos", color: "emerald" },
  "A4A1": { label: "Antiemético e antinaus...", color: "emerald" },
  "A4A2": { label: "Antiemético e antinaus...", color: "emerald" },
  "A4A9": { label: "Outros antiemético e a...", color: "emerald" },
  "A5A1": { label: "Coleréticos e coleciné...", color: "emerald" },
  "A5A2": { label: "Terapia dos cálculos b...", color: "emerald" },
  "A5A9": { label: "Outros produtos para d...", color: "emerald" },
  "A5B": { label: "Hepatoprotetores e lip...", color: "emerald" },
  "A6A1": { label: "Laxantes suavizadores ...", color: "emerald" },
  "A6A2": { label: "Laxantes estimulantes", color: "emerald" },
  "A6A3": { label: "Laxantes incrementador...", color: "emerald" },
  "A6A4": { label: "Laxantes enemas", color: "emerald" },
  "A6A6": { label: "Laxantes osmóticos", color: "emerald" },
  "A6A9": { label: "Outras drogas para con...", color: "emerald" },
  "A6B1": { label: "Agentes osmóticos de l...", color: "emerald" },
  "A7A": { label: "Antiinfecciosos intest...", color: "emerald" },
  "A7E1": { label: "Produtos aminosalicila...", color: "emerald" },
  "A7E2": { label: "Produtos corticoestero...", color: "emerald" },
  "A7F": { label: "Antidiarreicos micro-o...", color: "emerald" },
  "A7G": { label: "Repositores electrolít...", color: "emerald" },
  "A7H": { label: "Inibidores da motilidade", color: "emerald" },
  "A7X": { label: "Outros produtos para d...", color: "emerald" },
  "A8A": { label: "Preparações antiobesid...", color: "emerald" },
  "A9A": { label: "Digestivos, incluindo ...", color: "emerald" },
  "C10A1": { label: "Estatina, inibidores d...", color: "rose" },
  "C10A2": { label: "Fibratos", color: "rose" },
  "C10A3": { label: "Resinas trocadoras de ...", color: "rose" },
  "C10A4": { label: "Inibidores da pró-prot...", color: "rose" },
  "C10A9": { label: "Produtos reguladores d...", color: "rose" },
  "C10B": { label: "Preparações antiaterom...", color: "rose" },
  "C10C": { label: "Reguladores de gordura...", color: "rose" },
  "C11A1": { label: "Reguladores de lipídeo...", color: "rose" },
  "C1A1": { label: "Cardioglicosídeos", color: "rose" },
  "C1B": { label: "Antiarrítmicos cardíacos", color: "rose" },
  "C1C1": { label: "Estimulantes cardíacos...", color: "rose" },
  "C1C2": { label: "Agentes cardíacos dopa...", color: "rose" },
  "C1D": { label: "Terapia coronaria excl...", color: "rose" },
  "C1E": { label: "Nitritos e nitratos", color: "rose" },
  "C1F": { label: "Inotrópicos positivos", color: "rose" },
  "C1X": { label: "Todas outras preparaçõ...", color: "rose" },
  "C2A1": { label: "Anti-hipertensivo -açã...", color: "rose" },
  "C2A2": { label: "Anti-hipertensivo -açã...", color: "rose" },
  "C3A1": { label: "Agentes diuréticos pou...", color: "rose" },
  "C3A2": { label: "Diuréticos de alça", color: "rose" },
  "C3A3": { label: "Diuréticos tiazidas e ...", color: "rose" },
  "C3A5": { label: "Agentes diuréticos pou...", color: "rose" },
  "C3A9": { label: "Outros diuréticos", color: "rose" },
  "C4A1": { label: "Vasoterapêuticos cereb...", color: "rose" },
  "C4A2": { label: "Bloq. de cálcio com aç...", color: "rose" },
  "C5A1": { label: "Anti-hemorroidais com ...", color: "rose" },
  "C5A2": { label: "Anti-hemorroidais sem ...", color: "rose" },
  "C5B": { label: "Terapia antivaricosa t...", color: "rose" },
  "C5C": { label: "Vasoprotetores", color: "rose" },
  "C6A": { label: "Outros produtos cardio...", color: "rose" },
  "C6B1": { label: "Produtos hipertensão a...", color: "rose" },
  "C6B2": { label: "Produtos hipertensão a...", color: "rose" },
  "C6B3": { label: "Produtos para hiperten...", color: "rose" },
  "C6B9": { label: "Outros produtos para h...", color: "rose" },
  "C7A0": { label: "Beta-bloqueador", color: "rose" },
  "C7B1": { label: "Beta-bloqueador associ...", color: "rose" },
  "C8A": { label: "Bloq. de cálcio", color: "rose" },
  "C8B2": { label: "Bloq. de cálcio associ...", color: "rose" },
  "C9A": { label: "Inibidor da eca", color: "rose" },
  "C9B1": { label: "Inibidor da eca associ...", color: "rose" },
  "C9B3": { label: "Inibidor da eca associ...", color: "rose" },
  "C9C": { label: "Antag. angiotensina ii", color: "rose" },
  "C9D1": { label: "Antag. angiotensina ii...", color: "rose" },
  "C9D3": { label: "Antag. angiotensina ii...", color: "rose" },
  "C9D4": { label: "Antag. angiotensina ii...", color: "rose" },
  "C9D9": { label: "Antag. angiotensina ii...", color: "rose" },
  "C9X": { label: "Outros agentes com açã...", color: "rose" },
  "G03H0": { label: "Outros hormônios sexua...", color: "fuchsia" },
  "G04A9": { label: "Outros anti-sépticos u...", color: "fuchsia" },
  "G04B4": { label: "Produtos para incontin...", color: "fuchsia" },
  "G1A1": { label: "Tricomonicidas", color: "fuchsia" },
  "G1A2": { label: "Tricomonicidas s", color: "fuchsia" },
  "G1A3": { label: "Assoc. tricomonicidas", color: "fuchsia" },
  "G1B": { label: "Antifúngicos ginecológ...", color: "fuchsia" },
  "G1D": { label: "Antissépticos ginecoló...", color: "fuchsia" },
  "G2A": { label: "Indutores do parto inc...", color: "fuchsia" },
  "G2D": { label: "Inibidores da prolactina", color: "fuchsia" },
  "G2E": { label: "Inibidores do parto", color: "fuchsia" },
  "G2F": { label: "Hormônios sexuais s", color: "fuchsia" },
  "G2X9": { label: "Outros ginecológicos", color: "fuchsia" },
  "G3A1": { label: "Hormônios contraceptiv...", color: "fuchsia" },
  "G3A2": { label: "Hormônios contraceptiv...", color: "fuchsia" },
  "G3A3": { label: "Preparações contracept...", color: "fuchsia" },
  "G3A4": { label: "Preparações contracept...", color: "fuchsia" },
  "G3A5": { label: "Preparações com proges...", color: "fuchsia" },
  "G3A6": { label: "Contraceptivo de emerg...", color: "fuchsia" },
  "G3A9": { label: "Outros hormônios contr...", color: "fuchsia" },
  "G3B": { label: "Andrógenos excluindo g...", color: "fuchsia" },
  "G3C": { label: "Estrógenos excluindo g...", color: "fuchsia" },
  "G3D": { label: "Progestógenos excluind...", color: "fuchsia" },
  "G3F": { label: "Assoc. estrógenos e pr...", color: "fuchsia" },
  "G3G": { label: "Gonadotrofinas incluin...", color: "fuchsia" },
  "G3J": { label: "Moduladores seletivos ...", color: "fuchsia" },
  "G3X": { label: "Outros hormônios sexua...", color: "fuchsia" },
  "G4A1": { label: "Antibióticos urinários", color: "fuchsia" },
  "G4A9": { label: "Outros anti-séptcos ur...", color: "fuchsia" },
  "G4B9": { label: "Todos outros produtos ...", color: "fuchsia" },
  "G4C2": { label: "Bph antagonistas alfa-...", color: "fuchsia" },
  "G4C3": { label: "Bph inibidores da 5-al...", color: "fuchsia" },
  "G4C4": { label: "Bph assoc. de alfa-ant...", color: "fuchsia" },
  "G4C7": { label: "Bph assoc. de inibidor...", color: "fuchsia" },
  "G4C9": { label: "Outros produtos para hpb", color: "fuchsia" },
  "G4D4": { label: "Produtos para incontin...", color: "fuchsia" },
  "G4E1": { label: "Produtos para disfunçã...", color: "fuchsia" },
  "G4E9": { label: "Outros produtos para d...", color: "fuchsia" },
  "G4X": { label: "Todos os outros produt...", color: "fuchsia" },
  "H1C1": { label: "Hormônios liberadores ...", color: "purple" },
  "H1C2": { label: "Hormônios anticrescimento", color: "purple" },
  "H1C3": { label: "Hormônios de liberação...", color: "purple" },
  "H2A1": { label: "Corticoide", color: "purple" },
  "H2A2": { label: "Corticoide", color: "purple" },
  "H2B": { label: "Assoc. corticoide", color: "purple" },
  "H3A": { label: "Preparações para tireoide", color: "purple" },
  "H3B": { label: "Preparações antitireoi...", color: "purple" },
  "H4A": { label: "Calcitoninas", color: "purple" },
  "H4B": { label: "Glucagon", color: "purple" },
  "H4C": { label: "Hormônios do crescimento", color: "purple" },
  "H4D": { label: "Hormônios antidiuréticos", color: "purple" },
  "H4F": { label: "Produtos antiparatireo...", color: "purple" },
  "H4X": { label: "Outros hormônios e pre...", color: "purple" },
  "M1A1": { label: "Antirreumático não est...", color: "orange" },
  "M1A2": { label: "Antirreumático não est...", color: "orange" },
  "M1A3": { label: "Coxibs", color: "orange" },
  "M1C": { label: "Agentes anti-reumático...", color: "orange" },
  "M2A": { label: "Antirreumático e analg...", color: "orange" },
  "M3A": { label: "Relaxante muscular de ...", color: "orange" },
  "M3B": { label: "Relaxante muscular de ...", color: "orange" },
  "M4A": { label: "Antigotosos", color: "orange" },
  "M5B3": { label: "Bisfosfonatos para ost...", color: "orange" },
  "M5B4": { label: "Bisfosfonatos para alt...", color: "orange" },
  "M5X": { label: "Todos os outros fármac...", color: "orange" },
  "N1A1": { label: "Anestésicos gerais s", color: "violet" },
  "N1A2": { label: "Anestésicos gerais", color: "violet" },
  "N1B1": { label: "Anestésicos locais med...", color: "violet" },
  "N1B2": { label: "Anestésicos locais odo...", color: "violet" },
  "N1B3": { label: "Anestésicos locais s", color: "violet" },
  "N2A": { label: "Analgésicos narcóticos", color: "violet" },
  "N2B": { label: "Analgésico", color: "violet" },
  "N2B1": { label: "Analgésico sob prescrição", color: "violet" },
  "N2B2": { label: "Analgésico isentos de ...", color: "violet" },
  "N2C1": { label: "Antienxaquecoso triptâ...", color: "violet" },
  "N2C9": { label: "Todos as outras prepar...", color: "violet" },
  "N2D": { label: "Gabapentinoides", color: "violet" },
  "N3A": { label: "Antiepiléptico", color: "violet" },
  "N4A": { label: "Antiparkinsoniano", color: "violet" },
  "N5A1": { label: "Antipsicótico atípicos", color: "violet" },
  "N5A9": { label: "Antipsicótico convenci...", color: "violet" },
  "N5B1": { label: "Hipnótico/sedativo não...", color: "violet" },
  "N5B5": { label: "Hipnótico/sedativo her...", color: "violet" },
  "N5C": { label: "Ansiolítico", color: "violet" },
  "N6A2": { label: "Antidepressivo de orig...", color: "violet" },
  "N6A3": { label: "Estabilizadores do humor", color: "violet" },
  "N6A4": { label: "Antidepressivo ssri", color: "violet" },
  "N6A5": { label: "Antidepressivo snri", color: "violet" },
  "N6A9": { label: "Antidepressivo todos o...", color: "violet" },
  "N6B": { label: "Psicoestimulante", color: "violet" },
  "N6C": { label: "Assoc. psicolépticas e...", color: "violet" },
  "N6D": { label: "Nootrópicos", color: "violet" },
  "N6E": { label: "Neurotônicos e outros", color: "violet" },
  "N7A": { label: "Produtos para escleros...", color: "violet" },
  "N7B": { label: "Produtos antitabaco", color: "violet" },
  "N7C": { label: "Antivertiginosos", color: "violet" },
  "N7D1": { label: "Produtos antialzheimer...", color: "violet" },
  "N7D9": { label: "Todos os outros produt...", color: "violet" },
  "N7E": { label: "Produtos usados em dep...", color: "violet" },
  "N7F": { label: "Produtos usados em dep...", color: "violet" },
  "N7X": { label: "Todos os outros produt...", color: "violet" },
  "R03H2": { label: "Antiasmático/dpoc inib...", color: "cyan" },
  "R1A1": { label: "Corticoide nasais sem ...", color: "cyan" },
  "R1A3": { label: "Corticoide nasais com ...", color: "cyan" },
  "R1A4": { label: "Anti-infecciosos nasai...", color: "cyan" },
  "R1A6": { label: "Agentes antialérgicos ...", color: "cyan" },
  "R1A7": { label: "Descongestionantes nasais", color: "cyan" },
  "R1A9": { label: "Outras preparações tóp...", color: "cyan" },
  "R1B": { label: "Preparações sistêmicas...", color: "cyan" },
  "R2A": { label: "Preparações para garganta", color: "cyan" },
  "R3A2": { label: "Antiasmático/dpoc agon...", color: "cyan" },
  "R3A3": { label: "Antiasmático/dpoc agon...", color: "cyan" },
  "R3A4": { label: "Antiasmático/dpoc agon...", color: "cyan" },
  "R3B2": { label: "Antiasmático/dpoc xant...", color: "cyan" },
  "R3C2": { label: "Antiasmático/dpoc anti...", color: "cyan" },
  "R3D1": { label: "Antiasmático/dpoc cort...", color: "cyan" },
  "R3F1": { label: "Antiasmático/dpoc agon...", color: "cyan" },
  "R3J2": { label: "Antiasmático/dpoc anti...", color: "cyan" },
  "R3K1": { label: "Antiasmático/dpoc anti...", color: "cyan" },
  "R3K2": { label: "Antiasmático/dpoc anti...", color: "cyan" },
  "R3L1": { label: "Assoc. anticolinérgico...", color: "cyan" },
  "R3L2": { label: "Assoc. anticolinérgico...", color: "cyan" },
  "R3L3": { label: "Assoc anticolinérgicos...", color: "cyan" },
  "R3X2": { label: "Todos os outros produt...", color: "cyan" },
  "R4A": { label: "Unguentos percutâneos ...", color: "cyan" },
  "R5A": { label: "Antigripais sem antiin...", color: "cyan" },
  "R5C": { label: "Expectorantes", color: "cyan" },
  "R5D1": { label: "Antitussígenos", color: "cyan" },
  "R5D2": { label: "Antitussígenos associados", color: "cyan" },
  "R6A": { label: "Anti-histamínico", color: "cyan" },
  "R7B1": { label: "Moduladores do regulad...", color: "cyan" },
  "R7C": { label: "Surfactantes pulmonares", color: "cyan" },
  "R7D": { label: "Produtos de fibrose pu...", color: "cyan" },
};
